#!/usr/bin/env bash
#
# Arc Rector -- idempotent setup for an Oracle Cloud Always Free A1.Flex VM.
#
#   ./deploy/a1-setup.sh                bring the stack up
#   ./deploy/a1-setup.sh --gen-secrets  write a .env of fresh random credentials
#   ./deploy/a1-setup.sh --status       report only, change nothing
#   ./deploy/a1-setup.sh --pull-only    pull images, do not start
#
# Safe to re-run. It only ever touches containers in the `arc-rector` compose
# project, and it refuses to start if the box does not have room.
#
# THE BOX IS SHARED. Other people's containers run here. This script never
# prunes, never stops anything it did not start, and never runs a bare
# `docker compose down`.

set -euo pipefail

cd "$(dirname "$0")/.."

# docker compose reads .env by itself; this script does not, so the ARC_PORT_*
# settings below would disagree with the ports compose actually publishes.
# Import just those four -- never the secrets, and never by sourcing a file of
# unquoted values.
if [[ -f .env ]]; then
  while IFS='=' read -r _key _val; do
    [[ "$_key" =~ ^ARC_PORT_[A-Z]+$ ]] || continue
    # A real environment variable outranks .env, which is compose's own rule.
    [[ -n "${!_key:-}" ]] && continue
    export "${_key}=${_val//[$'\r\n \t']/}"
  done < .env
fi

readonly PROJECT="arc-rector"
readonly COMPOSE_FILE="docker-compose.a1.yml"
readonly MIN_RAM_MB=3000      # abort below this much AVAILABLE memory
readonly MIN_DISK_GB=10       # abort below this much free disk
readonly MODEL="${ARC_MODEL:-llama3.2:3b}"
readonly EMBED_MODEL="${ARC_EMBED_MODEL:-nomic-embed-text}"

# Host ports. Same names and defaults as docker-compose.a1.yml, so setting one
# in .env moves both the published port and every check below with it.
readonly PORT_UI="${ARC_PORT_UI:-8800}"
readonly PORT_LANGFUSE="${ARC_PORT_LANGFUSE:-3000}"
readonly PORT_QDRANT="${ARC_PORT_QDRANT:-6333}"
readonly PORT_OLLAMA="${ARC_PORT_OLLAMA:-11434}"

RED=$'\033[0;31m'; GREEN=$'\033[0;32m'; YELLOW=$'\033[1;33m'; BOLD=$'\033[1m'; NC=$'\033[0m'

info()  { printf '%s\n' "  $*"; }
ok()    { printf '%s\n' "  ${GREEN}ok${NC}   $*"; }
warn()  { printf '%s\n' "  ${YELLOW}warn${NC} $*"; }
die()   { printf '%s\n' "  ${RED}abort${NC} $*" >&2; exit 1; }
head()  { printf '\n%s\n%s\n' "${BOLD}$*${NC}" "$(printf '%.0s-' {1..70})"; }

[[ -f "$COMPOSE_FILE" ]] || die "$COMPOSE_FILE not found. Run this from the repo."

# ------------------------------------------------------------- credentials
# docker-compose.a1.yml declares every credential as ${VAR:?...}, so compose
# refuses to start until these exist. That is deliberate: the passwords in the
# local compose file are published in a public repository, and this box is
# shared and tunnel-reachable.
gen_secrets() {
  head "Generating credentials"
  command -v openssl >/dev/null 2>&1 || die "openssl is required to generate credentials."

  if [[ -f .env ]]; then
    warn ".env already exists -- leaving it alone."
    info "To rotate, move it aside first:  mv .env .env.old"
    return 0
  fi

  local old_umask; old_umask=$(umask); umask 077
  {
    printf '# Generated by deploy/a1-setup.sh --gen-secrets on %s\n' "$(date -u +%FT%TZ)"
    printf '# Secrets. Never commit this file -- .gitignore already excludes it.\n'
    printf 'POSTGRES_PASSWORD=%s\n'         "$(openssl rand -hex 24)"
    printf 'CLICKHOUSE_PASSWORD=%s\n'       "$(openssl rand -hex 24)"
    printf 'REDIS_PASSWORD=%s\n'            "$(openssl rand -hex 24)"
    printf 'MINIO_PASSWORD=%s\n'            "$(openssl rand -hex 24)"
    printf 'LANGFUSE_SALT=%s\n'             "$(openssl rand -hex 32)"
    # Langfuse rejects anything that is not exactly 256 bits of hex.
    printf 'LANGFUSE_ENCRYPTION_KEY=%s\n'   "$(openssl rand -hex 32)"
    printf 'LANGFUSE_NEXTAUTH_SECRET=%s\n'  "$(openssl rand -hex 32)"
    printf 'LANGFUSE_PUBLIC_KEY=pk-lf-%s\n' "$(openssl rand -hex 16)"
    printf 'LANGFUSE_SECRET_KEY=sk-lf-%s\n' "$(openssl rand -hex 24)"
    printf 'LANGFUSE_USER_PASSWORD=%s\n'    "$(openssl rand -base64 18 | tr -d '/+=')"
  } > .env
  umask "$old_umask"
  chmod 600 .env

  ok "wrote .env with 10 fresh credentials (mode 600)"
  info "Langfuse login: the email in docker-compose.a1.yml + LANGFUSE_USER_PASSWORD from .env"
  warn "back .env up somewhere safe; losing LANGFUSE_ENCRYPTION_KEY makes stored traces unreadable."
}

require_secrets() {
  [[ -f .env ]] && return 0
  die "no .env found. Generate one first:  ./deploy/a1-setup.sh --gen-secrets
        The compose file will not start on the repository's published passwords."
}

# ---------------------------------------------------------------- preflight
preflight() {
  head "Preflight -- measured, not assumed"

  command -v docker >/dev/null 2>&1 || die "docker is not installed."
  docker compose version >/dev/null 2>&1 || die "docker compose v2 is not available."
  docker info >/dev/null 2>&1 || die "cannot talk to the Docker daemon (is your user in the docker group?)."
  ok "docker $(docker --version | awk '{print $3}' | tr -d ,)"

  local arch; arch="$(uname -m)"
  info "architecture       $arch"
  [[ "$arch" == "aarch64" || "$arch" == "arm64" ]] || \
    warn "expected aarch64 (A1.Flex is Ampere ARM); continuing anyway."

  # Available, not free: on Linux most of "used" is reclaimable page cache.
  local ram_total ram_avail
  ram_total=$(awk '/MemTotal/{printf "%d", $2/1024}' /proc/meminfo)
  ram_avail=$(awk '/MemAvailable/{printf "%d", $2/1024}' /proc/meminfo)
  info "RAM total          ${ram_total} MB"
  info "RAM available      ${ram_avail} MB   (need >= ${MIN_RAM_MB} MB)"
  (( ram_avail >= MIN_RAM_MB )) || die \
    "only ${ram_avail} MB available, need ${MIN_RAM_MB} MB. Free memory or stop something first."
  ok "memory headroom is sufficient"

  local disk_avail_gb disk_pct
  disk_avail_gb=$(df -BG --output=avail . | tail -1 | tr -dc '0-9')
  disk_pct=$(df --output=pcent . | tail -1 | tr -dc '0-9')
  info "disk free          ${disk_avail_gb} GB   (need >= ${MIN_DISK_GB} GB, ${disk_pct}% used)"
  (( disk_avail_gb >= MIN_DISK_GB )) || die \
    "only ${disk_avail_gb} GB free, need ${MIN_DISK_GB} GB."
  ok "disk headroom is sufficient"

  # Name every container that is NOT ours, so the operator sees what they are
  # sharing the box with before anything starts.
  local others
  others=$(docker ps --format '{{.Names}}' | grep -v '^arc-rector-' || true)
  if [[ -n "$others" ]]; then
    head "Already running on this box (NOT ours -- do not touch)"
    printf '%s\n' "$others" | sed 's/^/    /'
    warn "this is a shared machine; never run 'docker system prune' here."
  fi

  # Refuse to fight over a port that something else already holds. If one of
  # these is taken, set the matching ARC_PORT_* in .env rather than editing the
  # compose file -- and never move a port that belongs to somebody else.
  head "Port check (all bind to 127.0.0.1 only)"
  local busy=0
  for port in "$PORT_QDRANT" "$PORT_LANGFUSE" "$PORT_UI" "$PORT_OLLAMA"; do
    if ss -ltn 2>/dev/null | grep -q ":${port}\b"; then
      if docker ps --format '{{.Names}}\t{{.Ports}}' | grep -q "arc-rector-.*:${port}"; then
        ok "port ${port} held by our own container (re-run, fine)"
      else
        warn "port ${port} is in use by something that is not ours"
        warn "  move OURS instead: set the matching ARC_PORT_* in .env"
        busy=1
      fi
    else
      ok "port ${port} free"
    fi
  done
  (( busy == 0 )) || die "a required port is taken by a foreign process. Resolve before continuing."
}

# ------------------------------------------------------------------- images
pull_images() {
  head "Pulling images (linux/arm64)"

  # `ui` is built from deploy/Dockerfile.ui, not pulled. A plain
  # `docker compose pull` tries to fetch arc-rector-ui:a1 from a registry,
  # fails, and takes the whole command down with it -- so nothing gets pulled
  # and setup aborts before it starts. --ignore-buildable skips exactly those
  # services; older compose builds do not have the flag, so name the pullable
  # services explicitly instead.
  local -a args=()
  if docker compose pull --help 2>&1 | grep -q -- '--ignore-buildable'; then
    args=(--ignore-buildable)
  else
    args=($(docker compose -f "$COMPOSE_FILE" config --services 2>/dev/null | grep -v '^ui$'))
  fi

  docker compose -f "$COMPOSE_FILE" pull --quiet "${args[@]}" 2>&1 | sed 's/^/    /' || \
    die "image pull failed. Check connectivity and that every tag has an arm64 variant."
  ok "images present"

  # Built separately, for the same reason. `up -d` would build it anyway; doing
  # it here keeps --pull-only meaning "fetch everything, start nothing".
  info "building the ui image (arc-rector-ui:a1)"
  docker compose -f "$COMPOSE_FILE" build ui 2>&1 | tail -3 | sed 's/^/    /' || \
    die "ui image build failed."
  ok "ui image built"
}

# -------------------------------------------------------------------- start
start_stack() {
  head "Starting the arc-rector stack"
  docker compose -f "$COMPOSE_FILE" up -d 2>&1 | sed 's/^/    /'
  ok "compose up issued"
}

wait_healthy() {
  head "Waiting for health"
  local deadline=$(( SECONDS + 300 ))

  _wait() {  # name, url, label
    local code
    while (( SECONDS < deadline )); do
      code=$(curl -s -o /dev/null -m 5 -w '%{http_code}' "$2" 2>/dev/null || true)
      # 401 is a healthy server: if ARC_UI_BASIC_AUTH_USER is set, the UI
      # challenges every route, and this probe has no credentials. What we are
      # asking is "did something answer", not "may I in".
      case "$code" in 200|401) ok "$3 responding"; return 0 ;; esac
      sleep 5
    done
    warn "$3 did not come up within the timeout"
    info "  logs: docker compose -f $COMPOSE_FILE logs $1 --tail 50"
    return 1
  }

  local failed=0
  _wait qdrant       "http://127.0.0.1:${PORT_QDRANT}/readyz"            "Qdrant"   || failed=1
  _wait langfuse-web "http://127.0.0.1:${PORT_LANGFUSE}/api/public/health" "Langfuse" || failed=1
  _wait ui           "http://127.0.0.1:${PORT_UI}/api/config"            "Web UI"   || failed=1
  if docker ps --format '{{.Names}}' | grep -q '^arc-rector-ollama$'; then
    _wait ollama     "http://127.0.0.1:${PORT_OLLAMA}/api/version"       "Ollama"   || failed=1
  fi
  return $failed
}

pull_models() {
  docker ps --format '{{.Names}}' | grep -q '^arc-rector-ollama$' || {
    info "ollama container not running; skipping model pull"; return 0; }

  head "Pulling models (skipped if already present)"
  local have
  have=$(docker exec arc-rector-ollama ollama list 2>/dev/null || true)
  for m in "$EMBED_MODEL" "$MODEL"; do
    if grep -q "^${m%%:*}" <<<"$have"; then
      ok "$m already present"
    else
      info "pulling $m (this is the slow part)"
      docker exec arc-rector-ollama ollama pull "$m" 2>&1 | tail -1 | sed 's/^/    /'
      ok "$m pulled"
    fi
  done
}

status() {
  head "Status"
  docker compose -f "$COMPOSE_FILE" ps \
    --format 'table {{.Name}}\t{{.Status}}\t{{.Ports}}' 2>/dev/null | sed 's/^/    /'

  head "Memory used by our containers"
  local names
  names=$(docker ps --filter "name=arc-rector-" --format '{{.Names}}' | tr '\n' ' ')
  if [[ -n "${names// /}" ]]; then
    # shellcheck disable=SC2086
    docker stats --no-stream --format 'table {{.Name}}\t{{.MemUsage}}\t{{.MemPerc}}' $names | sed 's/^/    /'
  fi
  printf '\n'
  awk '/MemAvailable/{printf "    host RAM still available: %d MB\n", $2/1024}' /proc/meminfo

  head "Local endpoints"
  cat <<EOF
    Web UI     http://127.0.0.1:${PORT_UI}
    Langfuse   http://127.0.0.1:${PORT_LANGFUSE}
    Qdrant     http://127.0.0.1:${PORT_QDRANT}/dashboard
    Ollama     http://127.0.0.1:${PORT_OLLAMA}
EOF

  local url_file="${ARC_TUNNEL_URL_FILE:-.arc_rector/tunnel-url.txt}"
  if [[ -s "$url_file" ]]; then
    head "Public URL"
    info "$(cat "$url_file")"
    if systemctl is-active --quiet arc-rector-tunnel.service 2>/dev/null; then
      ok "arc-rector-tunnel.service is running (survives a reboot)"
    else
      warn "not managed by systemd: it will not come back on its own."
      info "  ./deploy/tunnel.sh install-service"
    fi
    if [[ -z "${ARC_UI_BASIC_AUTH_USER:-}" ]] && ! grep -q '^ARC_UI_BASIC_AUTH_USER=.' .env 2>/dev/null; then
      warn "no ARC_UI_BASIC_AUTH_USER: that URL is public and UNAUTHENTICATED."
    fi
  fi

  head "Next"
  cat <<EOF
    Every port is bound to 127.0.0.1 and this box only exposes TCP 22, so
    nothing is publicly reachable except through a tunnel. To start one:

        ./deploy/tunnel.sh ${PORT_UI}                  # now, dies with the shell
        ./deploy/tunnel.sh install-service        # and after every reboot

    Set ARC_UI_BASIC_AUTH_USER and ARC_UI_BASIC_AUTH_PASSWORD in .env first.

    Verify the stack from the box itself:

        python3 -m arc_rector.demo

    Tear down ONLY this project (never a bare "docker compose down"):

        docker compose -f docker-compose.a1.yml down          # keep data
        docker compose -f docker-compose.a1.yml down -v       # delete volumes
EOF
}

main() {
  printf '%s\n' "${BOLD}Arc Rector -- Oracle A1 Always Free setup${NC}"
  case "${1:-}" in
    --gen-secrets) gen_secrets; exit 0 ;;
    --status)      status; exit 0 ;;
    --pull-only)   preflight; pull_images; exit 0 ;;
    "")            ;;
    *)             die "unknown option: $1" ;;
  esac

  require_secrets
  preflight
  pull_images
  start_stack
  wait_healthy || warn "some services are not healthy yet; check the logs above."
  pull_models
  status
  printf '\n  %sdone%s\n' "$GREEN" "$NC"
}

main "$@"
